name: Vector-Core
version: 1.9
api-version: 1.13
author: 54mpenguin
website: https://vectornetwork.me
description: The Core Plugin for Vector Network.
main: me.vectornetwork.core.Main
softdepend:
  - LuckPerms
  - Votifier
  - nuVotifier
  - MVdWPlaceholderAPI
  - SuperVanish
  - PremiumVanish

#######################################################################################[Commands]######################################################################

commands:
  vote:
    description: open the book gui for the vote links.
  vectorcorereload:
    description: reload the config for vector core.
    aliases:
      - vcreload
      - corereload
      - vectorreload
  autorestart:
    description: Main Command for the auto restart module.
    aliases:
      - re
      - autore
  ranktitle:
    description: Change a player's rank prefix.
    aliases:
      - titlerank
      - titleranks
      - titlesrank
      - titlesranks
      - rankstitles
      - ranktitles
      - rankstitle
  title:
    description: Main command for the titles module.
    aliases:
      - titles
      - tag
      - tags
  joinmessage:
    description: Main command for custom join messages.
    aliases:
      - joinm
      - jmessage
      - joinmsg
  leavemessage:
    description: Main command for custom leave messages.
    aliases:
      - leavem
      - lmessage
      - leavemsg
  gift:
    description: Send a player a gift.
  gifts:
    description: See and claim gifts sent to you by other players.

####################################################################################[Permissions]#########################################################################################

permissions:
  vectorcore.autorestart.admin:
    description: Allows the user to use /autorestart commands.
    default: op
  vectorcore.joinmessages.*:
    description: Main permission node for permission based join messages.
    default: op
  vectorcore.customjoinmessages:
    description: Main permission node for custom join messages.
    default: op
  vectorcore.customjoinmessages.admin:
    description: Allows the user to change other's join messages.
    default: op
  vectorcore.leavemessages.*:
    description: Main permission node for permission based leave messages.
    default: op
  vectorcore.customleavemessages:
    description: Main permission node for custom leave messages.
    default: op
  vectorcore.customleavemessages.admin:
    description: Allows the user to change other's leave messages.
    default: op
  vectorcore.titles.*:
    description: Main permission node for titles.
    default: op
  vectorcore.gifts.send:
    description: Send other players a gift.
    default: op
  vectorcore.gifts.claim:
    description: claim gifts that players have sent you.
    default: op
  vectorcore.ranktitles:
    description: allows players to change their rank prefix.
    default: op
  vorplexcore.server.switch:
    description: Allows the user to use the /server command.
    default: true